language: python
python:
  - 3.5

services:
  - docker

install:
  - docker build -t asciidoctor-pdf:1.50.alpha15 .
  - docker tag asciidoctor-pdf:1.50.alpha15 asciidoctor-pdf:latest

script:
  - docker images
